### ISSUE TITLE
Update Sonos and Cast configuration according to .78 breaking change

### ISSUE THREAD

**Issue by isabellaalstrom** [isabellaalstrom/HomeAssistantConfiguration#87]

**Comment by jcrowegitHu8** [comment]
I believe this may be my issue but I'm on the latest 0.72.1
https://community.home-assistant.io/t/0-72-1-update-how-to-fix-sonos-media-players-discovery/58271

Can you please add more details to this so I know what issue you are having is?

Mine is that I can't get any of my sonos speakers to show up as media players.
